### ISSUE TITLE
Dockerize the development (and possibly the production) environment 

### ISSUE THREAD

**Issue by murilo9** [SwitchbackTech/compass#173]
I don't know which version of Node and MongoDB the application is suposed to run on, but some developers may have different versions of Node/MongoDB on their machines, and setting up the development environment can differ considerably from one operational system to another (Windows, Mac, even different distros of Linux). We could standarize the development environment by dockerizing it, so we would make sure all developers will have the exact same development envrionment while coding, improving the maintanability on the long and avoiding possible version conflicts.
I don't know the specifics about the production environment (like production server's operating system, node version, etc) but if dockerizing the development envrionment manages to work, we could try to do it in prodution as well.

**Comment by tyler-dane** [comment]
I like this suggestion. This isn't a top priority since it's just you and more working on this now. For now, we can simply communicate if we need to adjust the node version on our machines or in prod. However, I expect this will become a higher priority once we have more contributors and deployments. 

Closing to cleanup the issues, but noting it for the future
